"""Build journals.js from the two Wiley APC spreadsheets.

Reads:
  - Wiley-Journal-APCs-OnlineOpen.xlsx   (Hybrid OA Journals Updated)
  - Wiley-Journal-APCs-Open-Access.xlsx  (OA APC Journals Updated)

Writes:
  - journals.js  (const JOURNALS = [...]; const SUBJECTS = [...];)

Usage:
  python3 build_data.py
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

import openpyxl

HERE = Path(__file__).resolve().parent
HYBRID_XLSX = HERE / "Wiley-Journal-APCs-OnlineOpen.xlsx"
GOLD_XLSX = HERE / "Wiley-Journal-APCs-Open-Access.xlsx"
OUT_JS = HERE / "journals.js"


def _clean_str(value: Any) -> str:
    if value is None:
        return ""
    s = str(value).strip()
    s = re.sub(r"\s+", " ", s)
    return s


def _to_number(value: Any) -> float | None:
    if value is None or value == "":
        return None
    if isinstance(value, (int, float)):
        return float(value)
    try:
        s = str(value).replace(",", "").strip()
        if not s:
            return None
        return float(s)
    except (TypeError, ValueError):
        return None


def _normalize_issn(value: Any) -> str:
    if value is None:
        return ""
    s = str(value).strip()
    if not s:
        return ""
    digits = re.sub(r"[^0-9Xx]", "", s)
    if len(digits) == 8:
        return f"{digits[:4]}-{digits[4:].upper()}"
    if len(digits) == 7:
        digits = "0" + digits
        return f"{digits[:4]}-{digits[4:].upper()}"
    return s


def _read_hybrid() -> list[dict[str, Any]]:
    wb = openpyxl.load_workbook(HYBRID_XLSX, data_only=True)
    ws = wb["Hybrid OA Journals Updated"]
    out: list[dict[str, Any]] = []
    for row in ws.iter_rows(min_row=9):
        title_cell = row[0]
        title = _clean_str(title_cell.value)
        if not title:
            continue
        url = title_cell.hyperlink.target if title_cell.hyperlink else ""
        subject = _clean_str(row[1].value)
        issn = _normalize_issn(row[2].value)
        license_ = _clean_str(row[3].value)
        usd = _to_number(row[4].value)
        gbp = _to_number(row[5].value)
        eur = _to_number(row[6].value)
        if usd is None and gbp is None and eur is None and not subject:
            continue
        out.append({
            "title": title,
            "subject": subject,
            "issn": issn,
            "license": license_,
            "usd": usd,
            "gbp": gbp,
            "eur": eur,
            "url": url,
            "type": "hybrid",
        })
    return out


def _read_gold() -> list[dict[str, Any]]:
    wb = openpyxl.load_workbook(GOLD_XLSX, data_only=True)
    ws = wb["OA APC Journals Updated"]
    out: list[dict[str, Any]] = []
    for row in ws.iter_rows(min_row=8):
        title_cell = row[0]
        title = _clean_str(title_cell.value)
        if not title or title.lower().startswith("journal name"):
            continue
        url = title_cell.hyperlink.target if title_cell.hyperlink else ""
        subject = _clean_str(row[1].value)
        issn = _normalize_issn(row[2].value)
        license_ = _clean_str(row[3].value)
        usd = _to_number(row[4].value)
        gbp = _to_number(row[5].value)
        eur = _to_number(row[6].value)
        if usd is None and gbp is None and eur is None and not subject:
            continue
        out.append({
            "title": title,
            "subject": subject,
            "issn": issn,
            "license": license_,
            "usd": usd,
            "gbp": gbp,
            "eur": eur,
            "url": url,
            "type": "gold",
        })
    return out


def main() -> None:
    hybrid = _read_hybrid()
    gold = _read_gold()
    all_journals = hybrid + gold
    all_journals.sort(key=lambda j: j["title"].lower())

    subjects = sorted({j["subject"] for j in all_journals if j["subject"]})

    payload = (
        "// Auto-generated by build_data.py. Do not edit by hand.\n"
        f"// Hybrid OA journals: {len(hybrid)}\n"
        f"// Gold OA journals:   {len(gold)}\n"
        f"// Total:              {len(all_journals)}\n\n"
        "const JOURNALS = "
        + json.dumps(all_journals, ensure_ascii=False, indent=2)
        + ";\n\nconst SUBJECTS = "
        + json.dumps(subjects, ensure_ascii=False, indent=2)
        + ";\n"
    )
    OUT_JS.write_text(payload, encoding="utf-8")
    print(f"Wrote {OUT_JS}  ({len(all_journals)} journals, {len(subjects)} subjects)")


if __name__ == "__main__":
    main()
